export const DATA_QUALITY_THRESHOLDS = {
  MISSING_DATA: {
    HIGH: 50,
    MODERATE: 20
  },
  ZERO_VALUES: {
    HIGH: 30
  },
  SAMPLE_SIZE: {
    MINIMUM: 10,
    SMALL: 20,
    ADEQUATE: 20
  }
};

export const QUALITY_SCORING = {
  ISSUE_PENALTY: {
    ERROR: 20,
    WARNING: 10,
    INFO: 2
  },
  SAMPLE_SIZE_PENALTY: {
    VERY_SMALL: 25,
    SMALL: 10
  },
  ALGORITHM_COMPARISON_PENALTY: {
    SINGLE_ALGORITHM: 30
  },
  DATA_COMPLETENESS_PENALTY: {
    HIGH_MISSING: 20,
    MODERATE_MISSING: 10
  }
};

export const STATISTICAL_THRESHOLDS = {
  P_VALUE_SIGNIFICANCE: 0.05,
  P_VALUE_HIGHLY_SIGNIFICANT: 0.01,
  CONFIDENCE_LEVEL: 0.95,
  OUTLIER_MULTIPLIER: 1.5
};

export const IMPROVEMENT_THRESHOLDS = {
  ZERO_THRESHOLD: 0.001,
  MAX_IMPROVEMENT_CAP: 100
};

export const CHART_THRESHOLDS = {
  PADDING_PERCENT: 0.15,
  MIN_PADDING: 1,
  Y_RANGE_MIN: 1
};
